library(DBI)
library(dbplyr)
library(forecast)
con <- dbConnect(RMySQL::MySQL(),
                 dbname = "testing",
                 port = 3306,
                 user = "root",
                 password = "root",
                 allow_local_infile=TRUE)
svBu <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Burgenland'"))
svKa <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Kaernten'"))
svNi <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Niederoesterreich'"))
svOb <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Oberoesterreich'"))
svOe <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Oesterreich'"))
svSa <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Salzburg'"))
svSt <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Steiermark'"))
svTi <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Tirol'"))
svVo <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Vorarlberg'"))
svWi <- c(dbGetQuery(con, "SELECT verbrauch FROM estats WHERE region='Wien'"))
svBuTS <- ts(svBu$verbrauch)
svKaTS <- ts(svKa$verbrauch)
svNiTS <- ts(svNi$verbrauch)
svObTS <- ts(svOb$verbrauch)
svOeTS <- ts(svOe$verbrauch)
svSaTS <- ts(svSa$verbrauch)
svStTS <- ts(svSt$verbrauch)
svTiTS <- ts(svTi$verbrauch)
svVoTS <- ts(svVo$verbrauch)
svWiTS <- ts(svWi$verbrauch)
svBuArima <- arima(svBuTS, order=c(2,1,1))
svKaArima <- arima(svKaTS, order=c(2,1,1))
svNiArima <- arima(svNiTS, order=c(2,1,1))
svObArima <- arima(svObTS, order=c(2,1,1))
svOeArima <- arima(svOeTS, order=c(2,1,1))
svSaArima <- arima(svSaTS, order=c(2,1,1))
svStArima <- arima(svStTS, order=c(2,1,1))
svTiArima <- arima(svTiTS, order=c(2,1,1))
svVoArima <- arima(svVoTS, order=c(2,1,1))
svWiArima <- arima(svWiTS, order=c(2,1,1))
svBuForecasts <- forecast(svBuArima, h=24)   # Burgenland
svKaForecasts <- forecast(svKaArima, h=24)   # Kärnten
svNiForecasts <- forecast(svNiArima, h=24)   # Niederösterreich
svObForecasts <- forecast(svObArima, h=24)   # Oberösterreich
svOeForecasts <- forecast(svOeArima, h=24)   # Österreich
svSaForecasts <- forecast(svSaArima, h=24)   # Salzburg
svStForecasts <- forecast(svStArima, h=24)   # Steiermark
svTiForecasts <- forecast(svTiArima, h=24)   # Tirol
svVoForecasts <- forecast(svVoArima, h=24)   # Voralberg
svWiForecasts <- forecast(svWiArima, h=24)   # Wien
spBu <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Burgenland'"))
spKa <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Kaernten'"))
spNi <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Niederoesterreich'"))
spOb <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Oberoesterreich'"))
spOe <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Oesterreich'"))
spSa <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Salzburg'"))
spSt <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Steiermark'"))
spTi <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Tirol'"))
spVo <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Vorarlberg'"))
spWi <- c(dbGetQuery(con, "SELECT preis FROM estats WHERE region='Wien'"))
spBuTS <- ts(spBu$preis)
spKaTS <- ts(spKa$preis)
spNiTS <- ts(spNi$preis)
spObTS <- ts(spOb$preis)
spOeTS <- ts(spOe$preis)
spSaTS <- ts(spSa$preis)
spStTS <- ts(spSt$preis)
spTiTS <- ts(spTi$preis)
spVoTS <- ts(spVo$preis)
spWiTS <- ts(spWi$preis)
spBuArima <- arima(spBuTS, order=c(1,1,2))
spKaArima <- arima(spKaTS, order=c(1,1,2))
spNiArima <- arima(spNiTS, order=c(1,1,2))
spObArima <- arima(spObTS, order=c(1,1,2))
spOeArima <- arima(spOeTS, order=c(1,1,2))
spSaArima <- arima(spSaTS, order=c(1,1,2))
spStArima <- arima(spStTS, order=c(1,1,2))
spTiArima <- arima(spTiTS, order=c(1,1,2))
spVoArima <- arima(spVoTS, order=c(1,1,2))
spWiArima <- arima(spWiTS, order=c(1,1,2))
spBuForecasts <- forecast(spBuArima, h=24)
spKaForecasts <- forecast(spKaArima, h=24)
spNiForecasts <- forecast(spNiArima, h=24)
spObForecasts <- forecast(spObArima, h=24)
spOeForecasts <- forecast(spOeArima, h=24)
spSaForecasts <- forecast(spSaArima, h=24)
spStForecasts <- forecast(spStArima, h=24)
spTiForecasts <- forecast(spTiArima, h=24)
spVoForecasts <- forecast(spVoArima, h=24)
spWiForecasts <- forecast(spWiArima, h=24)
emiBu <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Burgenland'"))
emiKa <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Kaernten'"))
emiNi <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Niederoesterreich'"))
emiOb <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Oberoesterreich'"))
emiOe <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Oesterreich'"))
emiSa <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Salzburg'"))
emiSt <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Steiermark'"))
emiTi <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Tirol'"))
emiVo <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Vorarlberg'"))
emiWi <- c(dbGetQuery(con, "SELECT emission FROM estats WHERE region='Wien'"))
emiBuTS <- ts(emiBu$emission)
emiKaTS <- ts(emiKa$emission)
emiNiTS <- ts(emiNi$emission)
emiObTS <- ts(emiOb$emission)
emiOeTS <- ts(emiOe$emission)
emiSaTS <- ts(emiSa$emission)
emiStTS <- ts(emiSt$emission)
emiTiTS <- ts(emiTi$emission)
emiVoTS <- ts(emiVo$emission)
emiWiTS <- ts(emiWi$emission)
emiBuArima <- arima(emiBuTS, order=c(2,1,1))
emiKaArima <- arima(emiKaTS, order=c(2,1,1))
emiNiArima <- arima(emiNiTS, order=c(2,1,1))
emiObArima <- arima(emiObTS, order=c(2,1,1))
emiOeArima <- arima(emiOeTS, order=c(2,1,1))
emiSaArima <- arima(emiSaTS, order=c(2,1,1))
emiStArima <- arima(emiStTS, order=c(2,1,1))
emiTiArima <- arima(emiTiTS, order=c(2,1,1))
emiVoArima <- arima(emiVoTS, order=c(2,1,1))
emiWiArima <- arima(emiWiTS, order=c(2,1,1))
emiBuForecasts <- forecast(emiBuArima, h=24)
emiKaForecasts <- forecast(emiKaArima, h=24)
emiNiForecasts <- forecast(emiNiArima, h=24)
emiObForecasts <- forecast(emiObArima, h=24)
emiOeForecasts <- forecast(emiOeArima, h=24)
emiSaForecasts <- forecast(emiSaArima, h=24)
emiStForecasts <- forecast(emiStArima, h=24)
emiTiForecasts <- forecast(emiTiArima, h=24)
emiVoForecasts <- forecast(emiVoArima, h=24)
emiWiForecasts <- forecast(emiWiArima, h=24)
siBu <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Burgenland'"))
siKa <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Kaernten'"))
siNi <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Niederoesterreich'"))
siOb <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Oberoesterreich'"))
siOe <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Oesterreich'"))
siSa <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Salzburg'"))
siSt <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Steiermark'"))
siTi <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Tirol'"))
siVo <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Vorarlberg'"))
siWi <- c(dbGetQuery(con, "SELECT import FROM estats WHERE region='Wien'"))
siBuTS <- ts(siBu$import)
siKaTS <- ts(siKa$import)
siNiTS <- ts(siNi$import)
siObTS <- ts(siOb$import)
siOeTS <- ts(siOe$import)
siSaTS <- ts(siSa$import)
siStTS <- ts(siSt$import)
siTiTS <- ts(siTi$import)
siVoTS <- ts(siVo$import)
siWiTS <- ts(siWi$import)
siBuArima <- arima(siBuTS, order=c(1,1,2))
siKaArima <- arima(siKaTS, order=c(1,1,2))
siNiArima <- arima(siNiTS, order=c(1,1,2))
siObArima <- arima(siObTS, order=c(1,1,2))
siOeArima <- arima(siOeTS, order=c(1,1,2))
siSaArima <- arima(siSaTS, order=c(1,1,2))
siStArima <- arima(siStTS, order=c(1,1,2))
siTiArima <- arima(siTiTS, order=c(1,1,2))
siVoArima <- arima(siVoTS, order=c(1,1,2))
siWiArima <- arima(siWiTS, order=c(1,1,2))
siBuForecasts <- forecast(siBuArima, h=24)
siKaForecasts <- forecast(siKaArima, h=24)
siNiForecasts <- forecast(siNiArima, h=24)
siObForecasts <- forecast(siObArima, h=24)
siOeForecasts <- forecast(siOeArima, h=24)
siSaForecasts <- forecast(siSaArima, h=24)
siStForecasts <- forecast(siStArima, h=24)
siTiForecasts <- forecast(siTiArima, h=24)
siVoForecasts <- forecast(siVoArima, h=24)
siWiForecasts <- forecast(siWiArima, h=24)
seBu <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Burgenland'"))
seKa <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Kaernten'"))
seNi <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Niederoesterreich'"))
seOb <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Oberoesterreich'"))
seOe <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Oesterreich'"))
seSa <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Salzburg'"))
seSt <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Steiermark'"))
seTi <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Tirol'"))
seVo <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Vorarlberg'"))
seWi <- c(dbGetQuery(con, "SELECT export FROM estats WHERE region='Wien'"))
seBuTS <- ts(seBu$export)
seKaTS <- ts(seKa$export)
seNiTS <- ts(seNi$export)
seObTS <- ts(seOb$export)
seOeTS <- ts(seOe$export)
seSaTS <- ts(seSa$export)
seStTS <- ts(seSt$export)
seTiTS <- ts(seTi$export)
seVoTS <- ts(seVo$export)
seWiTS <- ts(seWi$export)
seBuArima <- arima(seBuTS, order=c(1,1,2))
seKaArima <- arima(seKaTS, order=c(1,1,2))
seNiArima <- arima(seNiTS, order=c(1,1,2))
seObArima <- arima(seObTS, order=c(1,1,2))
seOeArima <- arima(seOeTS, order=c(1,1,2))
seSaArima <- arima(seSaTS, order=c(1,1,2))
seStArima <- arima(seStTS, order=c(1,1,2))
seTiArima <- arima(seTiTS, order=c(1,1,2))
seVoArima <- arima(seVoTS, order=c(1,1,2))
seWiArima <- arima(seWiTS, order=c(1,1,2))
seBuForecasts <- forecast(seBuArima, h=24)
seKaForecasts <- forecast(seKaArima, h=24)
seNiForecasts <- forecast(seNiArima, h=24)
seObForecasts <- forecast(seObArima, h=24)
seOeForecasts <- forecast(seOeArima, h=24)
seSaForecasts <- forecast(seSaArima, h=24)
seStForecasts <- forecast(seStArima, h=24)
seTiForecasts <- forecast(seTiArima, h=24)
seVoForecasts <- forecast(seVoArima, h=24)
seWiForecasts <- forecast(seWiArima, h=24)
rN1<-'Burgenland'
rN2<-'Kaernten'
rN3<-'Niederoesterreich'
rN4<-'Oberoesterreich'
rN5<-'Oesterreich'
rN6<-'Salzburg'
rN7<-'Steiermark'
rN8<-'Tirol'
rN9<-'Vorarlberg'
rN10<-'Wien'
voraussagen <- data.frame(region = c(rep(rN1,24),rep(rN2,24),rep(rN3,24),rep(rN4,24),rep(rN5,24),rep(rN6,24),rep(rN7,24),rep(rN8,24),rep(rN9,24),rep(rN10,24)),
                          vorverbrauch = c(svBuForecasts$mean,svKaForecasts$mean,svNiForecasts$mean,svObForecasts$mean,svOeForecasts$mean,svSaForecasts$mean,svStForecasts$mean,
                                           svTiForecasts$mean,svVoForecasts$mean,svWiForecasts$mean),
                          vorpreis = c(spBuForecasts$mean,spKaForecasts$mean,spNiForecasts$mean,spObForecasts$mean,spOeForecasts$mean,spSaForecasts$mean,spStForecasts$mean,
                                       spTiForecasts$mean,spVoForecasts$mean,spWiForecasts$mean),
                          voremission = c(emiBuForecasts$mean,emiKaForecasts$mean,emiNiForecasts$mean,emiObForecasts$mean,emiOeForecasts$mean,emiSaForecasts$mean,emiStForecasts$mean,
                                          emiTiForecasts$mean,emiVoForecasts$mean,emiWiForecasts$mean),
                          vorimport = c(siBuForecasts$mean,siKaForecasts$mean,siNiForecasts$mean,siObForecasts$mean,siOeForecasts$mean,siSaForecasts$mean,siStForecasts$mean,
                                        siTiForecasts$mean,siVoForecasts$mean,siWiForecasts$mean),
                          vorexport = c(seBuForecasts$mean,seKaForecasts$mean,seNiForecasts$mean,seObForecasts$mean,seOeForecasts$mean,seSaForecasts$mean,seStForecasts$mean,
                                        seTiForecasts$mean,seVoForecasts$mean,seWiForecasts$mean),
                          hour = (1:240))
dbWriteTable(con, value = voraussagen, name = "voraussagen", append = TRUE, temporary = FALSE, row.names=FALSE)
dbDisconnect(con)